import { Button } from "@/components/ui/button";
import Logo from "@/public/logo.webp";
import { ArrowLeft } from "lucide-react";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex min-h-svh flex-col items-center justify-center">
      <Button asChild variant="outline" className="absolute top-4 left-4">
        <Link href="/">
          <ArrowLeft className="size-4" />
          Back
        </Link>
      </Button>
      <div className="flex w-full max-w-sm flex-col gap-6">
        <Link
          href="/"
          className="flex items-center gap-2 self-center font-medium"
        >
          <Image
            src={Logo}
            alt="Logo"
            className="rounded-lg"
            width={32}
            height={32}
          />
          AuroraLMS.
        </Link>
        {children}
        <div className="text-muted-foreground text-center text-xs text-balance">
          By clicking continue, you agree to our{" "}
          <span className="hover:text-primary">Terms of service</span> and{" "}
          <span className="hover:text-primary">Privacy Policy</span>
        </div>
      </div>
    </div>
  );
}
